INSERT INTO ITEM(NAME) VALUES ('Franelas');
INSERT INTO ITEM(NAME) VALUES ('Tazas');
INSERT INTO ITEM(NAME) VALUES ('Cadenas');
INSERT INTO ITEM(NAME) VALUES ('Bandanas');
INSERT INTO ITEM(NAME) VALUES ('Frascos');